### ISSUE TITLE
Register the geolocation as a field type with bolt

### ISSUE THREAD

**Issue by jeffpfoster** [LordSimal/bolt-geolocation-field#7]
I get a configuration warning within the dashboard for bolt that the geolocation is not a valid field type.  Things seem to work as expected but shouldn't throw this warning.    I'm on 4.1.20.

**Comment by LordSimal** [comment]
I can reproduce the problem and will take a look on what needs to be changed on my side.

**Comment by LordSimal** [comment]
What I have debugged till now:

The notice is being thrown by https://github.com/bobdenotter/configuration-notices/blob/master/src/Checks.php#L255

Therefore for some reason my plugin is not present in the array which is being returned by 
`$this->fieldRepository::getFieldClassname($fieldType->get('type'))`

This function is a static function present in the bolt/core 
https://github.com/bolt/core/blob/4.1/src/Repository/FieldRepository.php#L138

And in there when all the classes are being loaded via `self::$em->getMetadataFactory()->getAllMetadata()` my extension is not present in that array.

Behind all that it has something do to with doctrine, because the Class doesn't show up in the
`vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php` function `getAllClassNames`

https://github.com/doctrine/persistence/blob/2.2.x/lib/Doctrine/Persistence/Mapping/Driver/MappingDriverChain.php#L102

Somewhere it has something to do how Symfony generates the cache because `getAllClassNames` uses drivers which are set in the `var/cache/dev/ContainerXYZ/App_KernelDevDebugContainer.php` file.

<img width="1792" alt="2021-06-06_15-10-13" src="https://user-images.githubusercontent.com/9105243/120925545-4f906c80-c6d9-11eb-98c0-37104980b007.png">

And I guess if "somehow" my extension would also be present in there then the notice would disappear.

But even if I add these drivers manually, it still show the notice.

Maybe it has to do with the name of my repository because it has dashes in the name?
